name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # Create and Activate Conda Env
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: cdp-data-interactive
        environment-file: environment.yml

    - name: Set up Quarto
      uses: quarto-dev/quarto-actions/setup@v2

    - name: Render and Publish
      shell: bash -l {0}
      uses: quarto-dev/quarto-actions/publish@v2
      with:
        target: gh-pages
        path: src/
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}